namespace AuthService.Models;

/// <summary>
/// Stores detailed error information for administrative diagnostics.
/// A user will typically report the <see cref="Reference"/> value (or at least
/// the approximate time) so administrators can locate the corresponding record.
/// </summary>
public class AuthError
{
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// UUID generated by frontend.
    /// </summary>
    public string Reference { get; set; } = default!;

    /// <summary>
    /// The full technical error.
    /// </summary>
    public string ErrorDetails { get; set; } = default!;

    /// <summary>
    /// When the error was stored.
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}
